language: rust
sudo: false
rust:
  - stable
  - nightly
env:
  global:
    secure: DcytHDVvTYGmBmiXufHVf2ftZ+DxIWELQFdlNDpUI56M/bvPNi/z371bxJleLhQ9JMd2VBAeZ60FXYHBcqv21N0ScnuUZ4miIrjesLSoNsaol2cwffbHsyyC7lb1ceABW237uufrROdRe/0/O+AzFiOIBL28omOTe08qW8D892c=
script:
  - cargo build
  - cargo test
  - cargo bench
after_success: 'curl https://raw.githubusercontent.com/iron/build-doc/master/build-doc.sh
  | sh '
